### ISSUE TITLE
Support for plantuml

### ISSUE THREAD

**Issue by milehimikey** [docuowl/docuowl#10]
This is a fantastic tool! Any plans for plantuml support?

**Comment by ofeefo** [comment]
Hi @milehimikey ! Thank you for the suggestion and sorry for our delay. 

We're not looking to implement PlantUML for now. It's a great tool, but users can use Markdown's support for indexing images as much as they need and we think that it will be a better approach for the tool. Supporting PlantUML would require us to find a way to execute a Java dependency, which is out of scope for this project.
