### ISSUE TITLE
Images do not resize in a responsive way

### ISSUE THREAD

**Issue by invakid404** [docuowl/docuowl#17]
Currently, images do not resize in a responsive way on smaller resolutions/mobile. It's a matter of a few lines of CSS, so I thought it wouldn't be too much of a problem to fix it :^)

Example of what I'm talking about:
![image](https://user-images.githubusercontent.com/38114607/117570048-507db080-b0d1-11eb-9741-651ed2aa97ff.png)

**Comment by heyvito** [comment]
Oh. That's unfortunate. 😅 
@coelhucas @matheusmedeiros Folks, can you take a look at this? Thanks!

**Comment by invakid404** [comment]
I noticed the PR which addresses this issue is merged. I built the master branch and I can confirm the issue has been resolved. Thanks, y'all!

**Comment by heyvito** [comment]
Hey @invakid404! Glad to know it solves your problem. I just pushed a new v0.2.2 release including pre-built binaries with this fix.

Thank you for the feedback! 🙌🏻
