### ISSUE TITLE
Request to improve installation instructions

### ISSUE THREAD

**Issue by mikaelvesavuori** [docuowl/docuowl#18]
Hi! Nice-looking project. I'd love to create more readable documentation with `docuowl` for some of my projects.

However, I might be daft, but I am not sure on the actual installation process, since this is not covered in any detail.

I am on macOS 11.2.3 (Macbook Pro M1) and using the Darwin ARM64 variant of `docuowl`. It can be directly executed (i.e. double-clicking the file) after allowing it in Security (being third party software). Adding it to the path variable in `.zshrc` (as I am assuming the intended installation would be) does not allow me to use it. Executing it with `sh docuowl` gives an error about being unable to execute a binary file.

This is all probably very easy to get working, but I'd be happy for advice and maybe having this updated in the docs for anyone having these "dumb" problems :)

**Comment by mikaelvesavuori** [comment]
Hey again. A brew tap would be a brilliant solution in my opinion.

Again, thanks for making `docuowl`!

**Comment by heyvito** [comment]
Hey @mikaelvesavuori! Just pushed the brew tap and updated the README, so you should be able to install it on your M1 using `brew install docuowl/tap/docuowl` 🎉 

Please let me know in case you run into any problems. I haven't had the opportunity to test it on Apple Silicon, but hopefully it will work just like any other platform. :)

Again, thank you for the feedback! It means a lot to us.

Best wishes! ✨

**Comment by mikaelvesavuori** [comment]
Brilliant! Works fine on my M1, so no worries there :)

Good job!
