### ISSUE TITLE
Dark mode switch

### ISSUE THREAD

**Issue by filipecalegario** [docuowl/docuowl#4]
Hi @heyvito, nice project! Is there an easy way to use a light color mode instead of the dark mode? On the Stripe API documentation page there is a dark mode switch, would it be possible to have it on the docuowl generated documentation too?

**Comment by heyvito** [comment]
Hey @filipecalegario! Thank you for the feedback!
Yes, I believe this is super tangible!

Pinging @matheusmedeiros @coelhucas. Can you folks check this out?

**Comment by heyvito** [comment]
Hi there @filipecalegario!
We will be releasing this feature together with #6, so I'll ping you here when this happens, ok?

Thank you again for the feedback! Hope you like the theme switcher! ✨

**Comment by heyvito** [comment]
Hey @filipecalegario!
Just a heads up that we just released v0.2, including the theme switcher! 🎉

**Comment by filipecalegario** [comment]
@heyvito Good news! I'll test ASAP. Thanks for the update! =D
