### ISSUE TITLE
Make the design responsive

### ISSUE THREAD

**Issue by poldi1405** [docuowl/docuowl#6]
I often scroll documentation on my phone (as to have a third screen) and currently, the mobile view is… somewhat lacking. I attached a screenshot to highlight what I mean. The main text is all squashed up while the examples take way too much space.

My suggestion would be to move the example column under their corresponding text to make it easier to read.
![photo5431762281198366932](https://user-images.githubusercontent.com/33086936/113735976-417b9b00-96ec-11eb-9f4d-735a0b8dedc1.jpg)

**Comment by heyvito** [comment]
Hi there! Thank you so much for the feedback!
@coelhucas and @matheusmedeiros are solving this one! Hang tight! 🙌🏻

**Comment by heyvito** [comment]
Hey @poldi1405, just released v0.2, adding responsiveness! 🎉
